name: inventory_repository
description: API Data manager package for inventory project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  http: ^0.13.4
  shared_preferences: ^2.0.12



dev_dependencies:
  flutter_lints: ^1.0.0